w4d5/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :albums, except: [:new, :index] do
    resources :tracks, only: [:new]
  end
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :tracks, except: [:new]

end

w4d5/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  band_id    :integer          not null
#  yr         :integer          not null
#  live       :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates :title, :yr, presence: true
  validates :live, inclusion: [true, false]

  belongs_to :band

  has_many :tracks
end

w4d5/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums

  has_many :tracks,
  through: :albums,
  source: :tracks

end

w4d5/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :bigint(8)        not null, primary key
#  album_id   :integer          not null
#  title      :string           not null
#  ord        :integer          not null
#  regular    :boolean          default(TRUE)
#  lyrics     :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ApplicationRecord
  validates :title, :ord, presence: true
  validates :regular, inclusion: [true, false]

  belongs_to :album

  has_one :band,
  through: :album,
  source: :band

end

w4d5/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :session_token, :password_digest,
  presence: true
  validates :email, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}
  before_validation :ensure_session_token

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
  end

  attr_reader :password

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def is_password?(pw)
    BCrypt::Password.new(password_digest).is_password?(pw)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    if user && user.is_password?(password)
      user
    else
      nil
    end
  end
  
end

w4d5/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :find_album, only: [:edit, :update, :destroy, :show]
  before_action :find_band, only: [:new]

  def new
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to band_url(@album.band_id)
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to new_band_album_url(@album.band_id)
    end
  end

  def show
    @band = Band.find(@album.band_id)
    render :show
  end

  def edit
    render :edit
  end

  def update
    if @album.update(album_params)
      redirect_to band_url(@album.band_id)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    band_id = @album.band_id
    if @album.destroy
      redirect_to band_url(band_id)
    else
      flash[:errors] = ["Album Couldn't Be Deleted"]
      redirect_to album_url(@album)
    end
  end

  private

  def find_album
    @album = Album.find_by(id: params[:id])
  end

  def find_band
    @band = Band.find_by(id: params[:band_id])
  end

  def album_params
    params.require(:album).permit(:title, :band_id, :yr, :live)
  end

end

w4d5/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def login!(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout!
    current_user.reset_session_token!
    @current_user = nil
    session[:session_token] = nil
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end


end

w4d5/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :find_band, only: [:destroy, :show, :update, :edit]
  def index
    @bands = Band.all
    render :index
  end

  def show
    if @band
      render :show
    else
      redirect_to bands_url
    end
  end

  def destroy
    unless @band.destroy
      flash[:errors] = ["The Band Couldn't Be Deleted"]
    end
    redirect_to bands_url
  end

  def update
    if @band
      @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = ["The Band You Are Editing Doesn't Exist"]
      render :edit
    end
  end

  def edit
    render :edit
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  private

  def find_band
    @band = Band.find_by(id: params[:id])
  end

  def band_params
    params.require(:band).permit(:name)
  end

end

w4d5/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Email and Password don't match"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end

end

w4d5/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :find_track, only: [:destroy, :show, :edit, :update]
  def show
    render :show
  end

  def new
    @track = Track.new
    render :new
  end

  private
  
  def track_params
    params.require(:track).permit(:title, :lyrics, :ord, :regular, :album_id)
  end

  def find_track
    @track = Track.find(params[:id])
  end

end

w4d5/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  def index
    @users = User.all
    render :index
  end

  def destroy
    @user = User.find_by(id: params[:id])
    if @user.destroy
      redirect_to users_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render 'shared/errors'
    end
  end


  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

w4d5/app/helpers/album_helper.rb
module AlbumHelper
end

w4d5/app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'/>".html_safe
  end
end

w4d5/app/helpers/band_helper.rb
module BandHelper
  

end

w4d5/app/helpers/tracks_helper.rb
module TracksHelper
end

w4d5/app/helpers/user_helper.rb
module UserHelper

  def sign_up_hash(type)
    result = Hash.new
    if type == :login
      result[:path] = session_url
      result[:button_label] = 'Sign-In'
    elsif type == :new
      result[:path] = new_user_url
      result[:button_label] = 'Sign-Up'
    end
    result
  end

end

w4d5/app/views/albums/_display.html.erb
<ul>
  <li style="font-size: 18px;font-weight:bold;">
    <a style="color:black;"href="<%= album_url(album) %>"><%= album.title %></a></li>
  <li><%= album.yr %></li>
  <li><%= album.live ? "Live" : "Studio" %></li>
</ul>

w4d5/app/views/albums/_form.html.erb
<form class="sign-up" action="<%= album.title ? album_url(album) : albums_url  %>" method="post">
  <% if album.title %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <%= auth_token %>
  <label>Title:
    <input type="text" name="album[title]" value="<%= album.title %>">
  </label>
  <label>Release Year:
    <input type="text" name="album[yr]" value="<%= album.yr %>">
  </label>
  <label>Band Name:
    <select class="" name="album[band_id]">
      <option disabled selected>--Choose A Band--</option>
      <% Band.all.each do |band| %>
      <option value="<%= band.id %>" <%= band.id == band_id.to_i ? "selected" : "" %> >
        <%= band.name %></option>
      <% end %>
    </select>
</label>
  <div class="radio">
    <label>Studio Album
      <input type="radio" name="album[live]" value="false"
      <%= album.live ? "" : "checked" %> >
    </label>
    <label>Live Album
      <input type="radio" name="album[live]" value="true"
      <%= album.live ? "checked" : "" %> >
    </label>
</div>

  <input type="submit" name="" value="submit">
</form>

w4d5/app/views/albums/edit.html.erb
<h2>Edit a Existing Album</h2>
<%= render 'shared/errors' %>
<%= render 'form', album: @album, band_id: @album.band_id %>

w4d5/app/views/albums/new.html.erb
<h2>Make a New Album</h2>
<%= render 'shared/errors' %>
<%= render 'form', album: @album, band_id: params[:band_id] %>

w4d5/app/views/albums/show.html.erb
<%= render "shared/errors" %>
<%= render 'display', album: @album %>
<a href="<%= edit_album_url(@album) %>">Edit this Album</a>
<a href="<%= band_url(@band) %>">Return to the <%= @band.name %> page</a>
<form class="" action="<%= album_url(@album) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="delete">
  <input type="submit" name="" value="Delete This Album">
</form>

w4d5/app/views/bands/_footer.html.erb
<a href="<%= bands_url %>">Return to All Bands Page</a>

w4d5/app/views/bands/_form.html.erb
<form class="" action="<%= type == :new ? bands_url : band_url(band) %>" method="post">
  <%= auth_token %>
  <% if type == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <input type="text" name="band[name]" value="<%= band.name %>">

  <input type="submit" name="" value="Submit">
</form>

w4d5/app/views/bands/edit.html.erb
<h1>Update Your Band</h1>
<%= render 'shared/errors' %>
<%= render 'form', band: @band, type: :edit %>
<%= render 'footer' %>

w4d5/app/views/bands/index.html.erb
<% @bands.each do |band| %>
  <ul style="padding:5px;">
    <li> <a class="band" href="<%= band_url(band) %>"><%= band.name %></a> </li><br>
  </ul>
<% end  %>

<a class="button" href="<%= new_band_url %>">Make a New Band</a>

w4d5/app/views/bands/new.html.erb
<h1>Make a New Band</h1>
<%= render 'shared/errors' %>
<%= render 'form', band: @band, type: :new %>
<%= render 'footer' %>

w4d5/app/views/bands/show.html.erb
<h1><%= @band.name %></h2>
  <br><br>
  <a href="<%= edit_band_url(@band) %>">Edit This Band</a>
  <br><br>
  <h2>Albums</h2>
  <ul>
    <% @band.albums.each do |album| %>
    <li><%= render 'albums/display', album: album %></li>
    <% end %>
  </ul>
  <form class="" action="<%= band_url(@band) %>" method="post">
    <%= auth_token %>
    <input type="hidden" name="_method" value="delete">
    <input type="submit" name="" value="Delete This Band">
  </form>
  <a href="<%= new_band_album_url(@band) %>">Add an Album for <%= @band.name %></a>
<%= render 'footer' %>

w4d5/app/views/layouts/_header.html.erb
<header>
  <h1>Music App</h1>

  <div class="user-header">
    <% if logged_in? %>
      <%= user.email %>
      <form class="logout" action="<%= session_url %>" method="post">
        <%= auth_token %>
        <input type="hidden" name="_method" value="delete">
        <input type="submit" name="" value="Logout!">
      </form>
      <% else %>
        <a class="login" href="<%= new_session_url %>">Log In!</a>
    <% end %>
  </div>

</header>

w4d5/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'css_reset' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render 'layouts/header', user: current_user %>
  <body>
    <%= yield %>
    <footer>
      <%= yield :footer %>
    </footer>
  </body>
</html>

w4d5/app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end  %>
<% end %>

w4d5/app/views/tracks/_form.html.erb
<form class="sign-up" action="<%= track.id ? track_url(track) : new_track_url %>" method="post">
  <%= auth_token %>
  <% if track.id %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <label>
    <input type="text" name="track[title]" value="<%= track.title %>">
  </label>
  <label>Album Title</label>
  <label>Lyrics (optional):
    <textarea name="track[lyrics]" rows="8" cols="80"><%= track.lyrics %></textarea>
  </label>


</form>

w4d5/app/views/tracks/new.html.erb
<h2>Make a New Track</h2>
<%= render 'shared/errors' %>
<%= render 'form', track: @track, album_id: params[:album_id] %>

w4d5/app/views/tracks/show.html.erb
<h1><%= @track.title %></h1>

<ul>
  <li><%= @track.ord %></li>
  <li><%= @track.lyrics %></li>
  <li><%= @track.regular ? "Standard Track" : "Bonus Track" %></li>
</ul>